### definitions ###

# default/library definitions
include $(DOGPACK)/scalar/lib/Makefile.defs

### targets ###

lib: $(ALL_OBJECTS)

include $(DOGPACK)/scalar/lib/Makefile.targets

### DO NOT remove this line - make depends on it ###
