function [outputdir_shouldname, params] = make_outputdirname(outputdir_in)
  setarg_outputdir
  params = get_GEM_params(outputdir);
  outputdir_shouldname = [ ... %'output' ...
    get_method_string(params) ...
    get_problem_string(params) ...
    get_model_string(params) ...
  ];
end

function method_string = get_method_string(params)
  assert(params.space_order==params.time_order);
  method_string = [ ... % ',,'
    sprintf('%03d',params.mx) 'x' sprintf('%03d',params.my) ...
    ... %',order=' num2str(params.space_order) ...
    ',cfl=' sprintf('%.2f', params.cflv(2)) ...
  ];
end

function problem_string = get_problem_string(params)
  problem_string = [ ...
    ',,scale=' sprintf('%03.1f', params.domain_scaling) ...
    get_mass_string(params) ...
  ];
end

function mass_string = get_mass_string(params)
  mass_string = [ ...
    ',m_i=' sprintf('%03.1f', params.ion_mass) ...
    ',mr=' sprintf('%03.1f', params.mass_ratio) ...
  ];
end

function model_string = get_model_string(params)
  resistivity_string = get_resistivity_string(params);
  model_string = [ ...
    ... %',,' params.model_name ...
    ... %',ion_iso_period=' sprintf('%05.2f',params.ion_iso_period) ...
    ',,tau_i=' num2str(params.ion_iso_period) ...
    ... %% sprintf('%05.2f',params.ion_iso_period) ...
    resistivity_string ...
  ];
end

function resistivity_string = get_resistivity_string(params)
  resistivity_string = '';
  if(params.slowing_period >= 0.)
    resistivity_string = [',slowing_period=' num2str(params.slowing_period)];
  end
  if(params.trigger_mui3 >=0.)
    resistivity_string = ...
      [resistivity_string ',trigger_mui3=' num2str(params.trigger_mui3)];
  end
  if(params.slowing_rate_slope >=0)
    resistivity_string = ...
      [resistivity_string ',slowing_rate_slope=' num2str(params.slowing_rate_slope)];
  end
end
