### definitions ###

# default/library definitions
include $(DOGPACK)/lib/4d/Makefile.defs
ALL_OBJECTS = $(LIB4D_OBJECTS)
ALL_SOURCES = $(LIB4D_SOURCES)

### targets ###

lib: $(LIB_CARTESIAN_OBJECTS_COMMON)

include $(DOGPACK)/lib/4d/Makefile.targets

### DO NOT remove this line - make depends on it ###
