
function [...
  nout    , ...
  tfinal  , ...
  dtv     , ...
  cflv    , ...
  nv      , ...
  method  , ...
  meqn    , ...
  mx      , ...
  my      , ...
  mbc     , ...
  xlow    , ...
  xhigh   , ...
  ylow    , ...
  yhigh   , ...
  mrestart, ...
  nstart  , ...
  datafmt ] ...
= read_dogpack_parameters2(readfile)

  % alternative implementation/invocation
  %
  global nout tfinal dtv cflv nv ...
     method meqn mx my mbc xlow xhigh ylow yhigh ...
     mrestart nstart datafmt;
  read_config_file(readfile);

%  fid=fopen(readfile,'r');
%  if(fid==-1)
%     error(['could not open file ' readfile]);
%  end
%  
%  dtv=zeros(1,2);
%  cflv=zeros(1,2);
%  method=zeros(1,7);
%  nout        = get_num(fid, 'nout'      );
%  tfinal      = get_num(fid, 'tfinal'    );
%  dtv(1)      = get_num(fid, 'dtv(1)'    );
%  dtv(2)      = get_num(fid, 'dtv(2)'    );
%  cflv(1)     = get_num(fid, 'cflv(1)'   );
%  cflv(2)     = get_num(fid, 'cflv(2)'   );
%  nv          = get_num(fid, 'nv'        );
%  method(1)   = get_num(fid, 'method(1)' );
%  method(2)   = get_num(fid, 'method(2)' );
%  method(3)   = get_num(fid, 'method(3)' );
%  method(4)   = get_num(fid, 'method(4)' );
%  method(5)   = get_num(fid, 'method(5)' );
%  method(6)   = get_num(fid, 'method(6)' );
%  method(7)   = get_num(fid, 'method(7)' );
%  meqn        = get_num(fid, 'meqn'      );
%  mx          = get_num(fid, 'mx'        );
%  my          = get_num(fid, 'my'        );
%  mbc         = get_num(fid, 'mbc'       );
%  xlow        = get_num(fid, 'xlow'      );
%  xhigh       = get_num(fid, 'xhigh'     );
%  ylow        = get_num(fid, 'ylow'      );
%  yhigh       = get_num(fid, 'yhigh'     );
%  mrestart    = get_num(fid, 'mrestart'  );
%  nstart      = get_num(fid, 'nstart'    );
%  datafmt     = get_num(fid, 'datafmt'   );
%
%  fclose(fid);
end

