#!/bin/sh

outputdir="$1/mesh_output";

# create output directory if it does not exist
if test ! -d $outputdir;
  then mkdir $outputdir;
fi

meshfiles="Unstructured_Mesh/mesh_output/*";

cp $meshfiles $outputdir;
