### definitions ###

# default/library definitions
include $(DOGPACK)/lib/3d/Makefile.defs
ALL_OBJECTS = $(LIB2D_OBJECTS)
ALL_SOURCES = $(LIB2D_SOURCES)

### targets ###

lib: $(LIB_CARTESIAN_OBJECTS_COMMON)

include $(DOGPACK)/lib/3d/Makefile.targets

### DO NOT remove this line - make depends on it ###
