# lib/sys/Makefile

### definitions ###

# default/library definitions
include $(DOGPACK)/lib/sys/Makefile.defs

# override defaults
CLEAN_FILES = *.o

### targets ###

lib: $(LIB_SYS_OBJECTS)

include $(DOGPACK)/lib/sys/Makefile.targets

### DO NOT remove this line - make depends on it ###
